#!/bin/bash

############################################
## Author : https://github.com/Eternln00b ##
##########################################################################################
## based on this script https://gist.github.com/stewdk/f4f36c3f6599072583bd40f15b5cdbef ##
##########################################################################################

source config_variables

finish () {
	
	sync
	local MNTPNTS=("${MNTROOTFS}proc" "${MNTROOTFS}dev/pts" "${MNTROOTFS}dev" "${MNTROOTFS}sys" "${MNTROOTFS}tmp" "${MNTBOOT}" "${MNTROOTFS}")
	for MNTPNT in "${MNTPNTS[@]}"
	do

		umount -l "${MNTPNT}" || true
	
	done

	kpartx -dvs ${IMGFILE} >/dev/null 2>&1
	mv ${IMGFILE} ${OUTPUT_IMG_DIR}
	umount -l ${MNTRAMDISK} || true
	rm -rf ${MNTROOTFS} ${MNTRAMDISK} || true
	
	if [[ ${IMG_COMPRESSION} ]];then

		echo -en "img compression !\n\n"
		xz -k --best ${OUTPUT_IMG_DIR}/${IMGNAME}.img

	fi

	chown -R $(id -nu 1000):$(id -nu 1000) ${WRKDIR}
	chmod -R 0755 ${WRKDIR}

}

packages() {

	local softwares=("g++-arm-linux-gnueabi" "gcc-aarch64-linux-gnu" "g++-aarch64-linux-gnu" "gcc-arm-linux-gnueabihf" "bison" "bc"
	"g++-arm-linux-gnueabihf" "gcc-arm-linux-gnueabi" "pkg-config-aarch64-linux-gnu" "pkg-config-arm-linux-gnueabihf" "flex" "parted" 
	"pkg-config-arm-linux-gnueabi" "debootstrap" "qemu-utils" "kpartx" "qemu-user-static" "binfmt-support" "libncurses5-dev" "git"
	"libssl-dev" "device-tree-compiler" "squashfs-tools" "wpasupplicant" "wget" "parallel")
	 

	for checking_softwares in "${softwares[@]}"
	do

		if [[ $(dpkg-query --show --showformat='${db:Status-Status}\n' ''$checking_softwares'') == "not-installed" ]];then 
	 
    		echo "The package $checking_softwares is being installed ..."
			apt install -y -qq -o=Dpkg::Use-Pty=0 $checking_softwares >/dev/null 2>&1

		fi

	done

}

Which_Raspberry_pi() {

	local LIGNE1="===================================================="
	local MESSAGE1=""
	MESSAGE1="\nwhich Raspberry Pi and which kernel please ?\n\n${LIGNE1}\n
	Raspberry Pi 4 in 64bits: a404ddedRpiDebian.sh -4 64bits\nRaspberry Pi 4 in 32bits: a404ddedRpiDebian.sh -4 32bits\n\n${LIGNE1}\n
	Raspberry Pi 3 in 64bits: a404ddedRpiDebian.sh -3 64bits\nRaspberry Pi 3 in 32bits: a404ddedRpiDebian.sh -3 32bits\n\n${LIGNE1}\n
	Raspberry Pi 2 in 32bits: a404ddedRpiDebian.sh -2\n\n${LIGNE1}\n\nRaspberry Pi 0,1 in 32bits: a404ddedRpiDebian.sh -1\n\n${LIGNE1}
	\nkernel configuration : a404ddedRpiDebian.sh -4 64bits -c\n\n"
	
	local MESSAGE2="\nWhich kernel please ? 64bits or 32bits ?\n\n"
	local MESSAGE3="\nThe first argument do not require an argument\n\n"
	
	[[ $1 == "MESSAGE1" ]] && local MESSAGE=$MESSAGE1
	[[ $1 == "MESSAGE2" ]] && local MESSAGE=$MESSAGE2
	[[ $1 == "MESSAGE3" ]] && local MESSAGE=$MESSAGE3
	
	echo -en "$MESSAGE" | tr -d "\t"

}

Options_processing() {

	while getopts ":4:3:21cx" options ; do
	case $options in

		4)

			if [[ $OPTARG == "64bits" || $OPTARG == "32bits" ]];then

				[[  $OPTARG == "64bits" ]] && KERNEL="kernel8" 
				[[  $OPTARG == "32bits" ]] && KERNEL="kernel7l" 
				OS=${OPTARG}
				pi="4"

			fi		
			;;

		3)

			if [[ $OPTARG == "64bits" || $OPTARG == "32bits" ]];then

				[[  $OPTARG == "64bits" ]] && KERNEL="kernel8" 
				[[  $OPTARG == "32bits" ]] && KERNEL="kernel7" 
				OS=${OPTARG}
				pi="3"

			fi	
			;;

		2)

			KERNEL="kernel7"
			pi="2"
			;;

		1)

			KERNEL="kernel"	
			pi="1"
			;;	

		c)

			KERNEL_CONFIGURE=true
			;;
		
		x)

			IMG_COMPRESSION=true
			;;
		
		:)

			Which_Raspberry_pi "MESSAGE2"
			exit 1
			;;


		\?)

			Which_Raspberry_pi "MESSAGE1" 
			exit 1
			;;

		*)

			Which_Raspberry_pi "MESSAGE1" 
			exit 1
			;;

	esac
	done

	if [[ ! -d ${TMP_DIR} ]];then 

		mkdir -p ${TMP_DIR}

	else 

		rm -rf ${TMP_DIR}/*

	fi 

	[[ -d ${OUTPUT_IMG_DIR} ]] && rm -rf ${OUTPUT_IMG_DIR}
	[[ ! -f ${TMP_DIR}/exported-variables ]] && touch ${TMP_DIR}/exported-variables
	[[ ! -d ${OUTPUT_IMG_DIR} ]] && mkdir -p ${OUTPUT_IMG_DIR}
	[[ ! -d ${WRKDIR} ]] && mkdir -p ${WRKDIR}

	if [[ ${pi} == "4" || ${pi} == "3" ]];then

		echo "${pi}:${OS}:${KERNEL}" >> ${TMP_DIR}/config.kernel.tmp

	else

		echo "${pi}:${KERNEL}" >> ${TMP_DIR}/config.kernel.tmp

	fi
	
}

set_compiler() {

	if [[ $1 == "kernel8" ]];then

		DARCH="arm64"
		KARCH="arm64"
		QARCH="aarch64"
		CROSS_COMPILER=aarch64-linux-gnu-
		KERNEL_IMG="Image"
		[[ $pi == "3" ]] && RPI_DEFCONFIG="bcmrpi3_defconfig"
		[[ $pi == "4" ]] && RPI_DEFCONFIG="bcm2711_defconfig"

	else

		DARCH="armhf"
		KARCH="arm"
		QARCH="arm"
		CROSS_COMPILER=arm-linux-gnueabihf-
		KERNEL_IMG="zImage"
		[[ $1 == "kernel" ]] && RPI_DEFCONFIG="bcmrpi_defconfig"
		[[ $1 == "kernel7" ]] && RPI_DEFCONFIG="bcm2709_defconfig"
		[[ $1 == "kernel7l" ]] && RPI_DEFCONFIG="bcm2711_defconfig"

	fi

	if [[ $pi == "1" ]]; then

		IMGNAME=Debian_${RELEASE}_${QARCH}_rpi0_1		

	else

		IMGNAME=Debian_${RELEASE}_${QARCH}_rpi${pi}

	fi 

	IMGFILE=${MNTRAMDISK}${IMGNAME}.img

}

check_if_downloaded(){

	local folder=$1
	source /tmp/Debian_Rpi/exported-variables

	[[ ! -f ${TMP_DIR}/sources ]] && touch ${TMP_DIR}/sources

	if [[ ! -d ${folder} ]];then 

		echo ${folder} >> ${TMP_DIR}/sources

	else

		if [[ -d ${folder} && ! -f "${folder}/Debian_${RELEASE}_${QARCH}.tar.gz" ]];then

			echo ${folder} >> ${TMP_DIR}/sources

		fi 

	fi
	
}

download_source() {

	source /tmp/Debian_Rpi/exported-variables
	local sources=$1
	local project=${sources//${WRKDIR}/} 
	
	if [[ "$(grep -oP '('${project}')' /tmp/Debian_Rpi/sources)" == "/rootfs" ]];then

		local rootfs_img=/tmp/rootfs_base.img
		qemu-img create -f raw ${rootfs_img} 400M > /dev/null
		(echo "n"; echo "p"; echo "1"; echo ""; echo ""; echo "w") | fdisk ${rootfs_img} > /dev/null
		local MNTBASEROOTFS=/mnt/rpi-base-rootfs/
		[[ ! -d ${sources} ]] && mkdir -p ${sources}
		[[ ! -d ${MNTBASEROOTFS} ]] && mkdir -p ${MNTBASEROOTFS}
		local PACKAGES='nano,ntp,openssh-server,perl,sudo,wget'
		local LOOPDEVSTMP=$(kpartx -avs /tmp/rootfs_base.img | awk '{print $3}')
		local LOOPROOTFSTMP=/dev/mapper/$(echo ${LOOPDEVSTMP} | awk '{print $1}')
		mkfs.ext4 ${LOOPROOTFSTMP} >/dev/null 2>&1
		mount ${LOOPROOTFSTMP} ${MNTBASEROOTFS}
		/bin/bash -c "xterm -T 'debian '${RELEASE}' base' -geometry 215-100+5 -e 'debootstrap --keyring '${KEYRING}' --include=ca-certificates --include='${PACKAGES}' --arch='${DARCH}' '${RELEASE}' '${MNTBASEROOTFS}' '${APT_SOURCE}''"
		tar --xform s:'^./':: --exclude="lost+found" --exclude="debootstrap" -zcf ${sources}/Debian_${RELEASE}_${QARCH}.tar.gz -C ${MNTBASEROOTFS} . 
		umount -l ${MNTBASEROOTFS} || true
		kpartx -dvs ${rootfs_img} >/dev/null 2>&1
		rm -rf ${MNTBASEROOTFS} ${rootfs_img}
		
	else

		local gitlink="https://github.com/${project}.git"

		if [[ "${project}" == "raspberrypi/linux" && "${KARCH}" == "arm64" ]];then

			xterm -geometry position=+100 -e "git clone --branch rpi-5.15.y --single-branch ${gitlink} ${sources}"

		else

			xterm -geometry position=80 -e "git clone --single-branch ${gitlink} ${sources}"
		
		fi

	fi

}

pre_kernel_compile() {

	local kernel_config=${WRKDIR}/raspberrypi/linux/config.kernel
	local kernel_config_tmp=${TMP_DIR}/config.kernel.tmp
	local kernel_rpi=${WRKDIR}/raspberrypi/linux/arch/${KARCH}/boot/${KERNEL_IMG}

	if [[ ! -f ${kernel_config} ]];then 

		mv ${kernel_config_tmp}	${kernel_config}

	else

		if [[ $(diff -s ${kernel_config_tmp} ${kernel_config} > /dev/null ; echo $?) -eq 1 || ${KERNEL_CONFIGURE} ]];then

			[[ -f ${kernel_rpi} ]] && rm -rf ${kernel_rpi}
			rm -rf ${kernel_config}
			cd ${WRKDIR}/raspberrypi/linux
			make -j${PROCS} mrproper &> /dev/null
	    		make -j${PROCS} distclean &> /dev/null
			make -j${PROCS} clean &> /dev/null
			mv ${kernel_config_tmp}	${kernel_config}

		fi

	fi
    
}

kernel_compile() {

	source ${TMP_DIR}/exported-variables
	echo -en "Building kernel. This takes a while ... \n\n"
	cd ${WRKDIR}/raspberrypi/linux
	make ARCH=${KARCH} CROSS_COMPILE=${CROSS_COMPILER} ${RPI_DEFCONFIG} -j${PROCS} &> /dev/null
	[[ ${KERNEL_CONFIGURE} ]] && xterm -geometry 210x200+100-10 -e 'make ARCH='${KARCH}' CROSS_COMPILE='${CROSS_COMPILER}' -j'${PROCS}' menuconfig '
	xterm -geometry 80 -e 'make ARCH='${KARCH}' CROSS_COMPILE='${CROSS_COMPILER}' '${KERNEL_IMG}' modules dtbs -j'${PROCS}''
		
}

check_kernel_version() {

	local kernel_version=$1
	local versions=$(git ls-remote --heads https://github.com/raspberrypi/linux | sed -r 's/\S+//1;s|[[:space:]]refs/heads/||')
	if [[ -n $(echo ${versions} | grep -oP '('${kernel_version}')' ) ]];then

		exit 0

	else

		exit 1

	fi

}
 
Debian_build() {

	source ${TMP_DIR}/exported-variables
	local BOOT_PART_SIZE=$1
	local IMG_SIZE=$2
	local BASEROOTFS=${WRKDIR}/rootfs/Debian_${RELEASE}_${QARCH}.tar.gz
	local MOUNTS_DIRS=("proc" "dev" "dev/pts" "sys" "tmp")

	echo -en "Building the Debian image !\n\n"

	[[ ! -d ${MNTRAMDISK} ]] && mkdir -p ${MNTRAMDISK}
	[[ ! -d ${MNTROOTFS} ]] && mkdir -p ${MNTROOTFS}

	mount -t tmpfs -o size=2g tmpfs ${MNTRAMDISK}

	qemu-img create -f raw ${IMGFILE} ${IMG_SIZE} > /dev/null 
	(echo "n"; echo "p"; echo "1"; echo "2048"; echo "+${BOOT_PART_SIZE}"; echo "n"; echo "p"; echo "2"; echo ""; echo ""; 
 	 echo "t"; echo "1"; echo "c"; echo "w") | fdisk ${IMGFILE} > /dev/null

	LOOPDEVS=$(kpartx -avs ${IMGFILE} | awk '{print $3}')
	LOOPDEVBOOT=/dev/mapper/$(echo ${LOOPDEVS} | awk '{print $1}')
	LOOPDEVROOTFS=/dev/mapper/$(echo ${LOOPDEVS} | awk '{print $2}')

	mkfs.vfat ${LOOPDEVBOOT} >/dev/null 2>&1
	mkfs.ext4 ${LOOPDEVROOTFS} >/dev/null 2>&1

	fatlabel ${LOOPDEVBOOT} Boot >/dev/null 2>&1
	e2label ${LOOPDEVROOTFS} Debian >/dev/null 2>&1

	mount ${LOOPDEVROOTFS} ${MNTROOTFS}
	tar -C ${MNTROOTFS} -xf ${BASEROOTFS}
	mount ${LOOPDEVBOOT} ${MNTBOOT}
	
	for mount_dir in "${MOUNTS_DIRS[@]}"
	do

		mount -o bind /${mount_dir} ${MNTROOTFS}${mount_dir}

	done
	
	cp $( which qemu-${QARCH}-static ) ${MNTROOTFS}usr/bin/
	cp ${WRKDIR}/raspberrypi/firmware/boot/bootcode.bin ${WRKDIR}/raspberrypi/firmware/boot/fixup*.dat ${WRKDIR}/raspberrypi/firmware/boot/start*.elf ${MNTBOOT}
	sed -e "s|KERNEL=|KERNEL=${KERNEL}|" -i ${TMP_DIR}/chroot_scripts/package_debian
	chmod +x ${TMP_DIR}/chroot_scripts/package_debian
	xterm -T 'OS configuration' -geometry 190x180+90-20 -e 'chroot '${MNTROOTFS}' '${TMP_DIR}'/chroot_scripts/package_debian'
	# xterm -T 'debuging' -geometry 210x200+100-10 -e 'chroot '${MNTROOTFS}' /bin/bash'
	
}

######################
## script checkings ##
######################

if [[ $(id -u) -ne 0 || $( curl -A "Mozilla/5.0" -Lfs https://www.google.com -o /dev/null; echo $? ) -ne 0 ]]; then

	echo "[!] This script must run as root or you are not connected to internet "
	exit 1

fi

if [[ $(lsb_release -i | grep -o "Ubuntu") != "Ubuntu" || -z $( command -v lsb_release ) ]];then

	echo "[!] This script was made only for Ubuntu"
	exit 1

fi

if [[ -z $( which dpkg-query ) || -z $( which apt ) ]];then
	
	echo "[!] dpkg-query or apt are there ?"
	exit 1

fi

if [[ "$#" -eq 0 ]];then
	
	Which_Raspberry_pi "MESSAGE1"
	exit 1 

elif [[  $3 == "-c" ]];then

	[[ $1 == "-1" || $1 == "-2" ]] && { 
		
		Which_Raspberry_pi "MESSAGE3"
		exit 1 

	}
	
fi

######################
## script beginning ##
######################

Options_processing "$@"
packages
set_compiler "$KERNEL"

/bin/cat /dev/null >> ${TMP_DIR}/exported-variables
/bin/cat <<exported_variables >> ${TMP_DIR}/exported-variables
APT_SOURCE=${APT_SOURCE}
CROSS_COMPILER=${CROSS_COMPILER}
DARCH=${DARCH}
RELEASE=${RELEASE}
HOSTNAME_RPI=${HOSTNAME_RPI}
IMGFILE=${IMGFILE}
KARCH=${KARCH}
KERNEL_IMG=${KERNEL_IMG}
KERNEL=${KERNEL}
KEYBOARD=${KEYBOARD}
KEYRING=${KEYRING}
LOCALE=${LOCALE}
MNTBOOT=${MNTBOOT}
MNTRAMDISK=${MNTRAMDISK}
MNTROOTFS=${MNTROOTFS}
QARCH=${QARCH}
RPI_DEFCONFIG=${RPI_DEFCONFIG}
PASSWORD=${PASSWORD}
RPIUSER=${RPIUSER}
STANDARD=${STANDARD}
TMP_DIR=${TMP_DIR}
WRKDIR=${WRKDIR}
PROCS=$(nproc)
exported_variables

[[ -f ${TMP_DIR}/sources ]] && rm -rf ${TMP_DIR}/sources
rpi_sources_folders=("${WRKDIR}/rootfs" "${WRKDIR}/raspberrypi/linux" "${WRKDIR}/raspberrypi/firmware")

for sources in "${rpi_sources_folders[@]}"
do

	check_if_downloaded $(echo ${sources})

done

if [[ -f ${TMP_DIR}/sources ]];then

	sources_download=$(cat ${TMP_DIR}/sources | wc -l)

	if [[ sources_download -ge 1 && sources_download -le 3 ]];then

		echo -en "\nDownloading the sources codes\n\n"
		export -f download_source
		/bin/bash -c "/usr/bin/parallel -j${PROCS} download_source < ${TMP_DIR}/sources" 
		
	else

		if [[ sources_download -eq 0 ]];then

			echo -en "We can build the image\n\n"
		
		else

			echo "it's weird"	
			exit 1

		fi

	fi

fi

[[ -n ${KERNEL_CONFIGURE} ]] && echo "KERNEL_CONFIGURE=${KERNEL_CONFIGURE}" >> ${TMP_DIR}/exported

if [[ -n $KERNEL ]];then

	trap finish EXIT

	cp -r $(pwd)/chroot_scripts ${TMP_DIR}
	cp -r $(pwd)/os_items ${TMP_DIR}
	sed -e '4i\RPIUSER='"$RPIUSER"'\nHOSTNAME_RPI='"$HOSTNAME_RPI"'' -i ${TMP_DIR}/chroot_scripts/package_debian

 	Debian_build 70M 960M
	pre_kernel_compile

	[[ ! -f ${WRKDIR}/raspberrypi/linux/arch/${KARCH}/boot/${KERNEL_IMG} ]] && kernel_compile 

	echo -en "Installing the kernel ...\n\n"
	cp ${WRKDIR}/raspberrypi/linux/arch/${KARCH}/boot/${KERNEL_IMG} ${MNTBOOT}${KERNEL}.img
    	[[ ${KARCH} == "arm" ]] && cp ${WRKDIR}/raspberrypi/linux/arch/${KARCH}/boot/dts/*.dtb ${MNTBOOT}
	[[ ${KARCH} == "arm64" ]] && cp ${WRKDIR}/raspberrypi/linux/arch/${KARCH}/boot/dts/broadcom/*.dtb ${MNTBOOT}
    	cd ${WRKDIR}/raspberrypi/linux
    	make ARCH=${KARCH} CROSS_COMPILE=${CROSS_COMPILER} INSTALL_MOD_PATH=${MNTROOTFS} modules_install -j ${JOBS} &> /dev/null
	
else

	Which_Raspberry_pi "MESSAGE2"
	exit 1

fi
